# Generated by Django 3.2.4 on 2021-07-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KNB', '0002_balance_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
